[build]
  publish = "public"
  command = "npm run build"

[functions]
  directory = "netlify/edge-functions"

[[edge_functions]]
  function = "set-cookie"
  path = "/set-cookie"

[[edge_functions]]
  function = "clear-cookie"
  path = "/clear-cookie"